[[LightGBM]]
arch = "aarch64"
git-tree-sha1 = "e699fe078f736f8461f5528d2ef669a2de38d552"
os = "macos"

    [[LightGBM.download]]
    sha256 = "91b5addb33244cd3c67f481ac46609a8d98eae9943bc7922e568f37252997b18"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.aarch64-apple-darwin.tar.gz"
[[LightGBM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33b6b0a0f0b9b7d35c4ebc847a99309fefc1c18a"
libc = "glibc"
os = "linux"

    [[LightGBM.download]]
    sha256 = "a0e2465060cd3ce8c5266df8d91125c10069ee00422cb95bb13e9d390a5dabe5"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.aarch64-linux-gnu-cxx03.tar.gz"
[[LightGBM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "063f18fed6615bf6526349b84cb19b61ce58fbf9"
libc = "glibc"
os = "linux"

    [[LightGBM.download]]
    sha256 = "5ae9cf23a84a41f7da526745ffe888faaf701c1497d97f1a91e3a1c1ae3ab8fa"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.aarch64-linux-gnu-cxx11.tar.gz"
[[LightGBM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15d33b309a40c65b45c29bfeae1757ccc242e5c0"
libc = "musl"
os = "linux"

    [[LightGBM.download]]
    sha256 = "f15722e586a8fdfdfc5eb9857fecb04799f859204b596a5e3bde1605d891b2de"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.aarch64-linux-musl-cxx03.tar.gz"
[[LightGBM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05175d16078279120b2d535fb4bf2503c383cfc6"
libc = "musl"
os = "linux"

    [[LightGBM.download]]
    sha256 = "2742b627ad0f2fc400a9e523114784b33b6d10156e90ed481d6a7387db693cc9"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.aarch64-linux-musl-cxx11.tar.gz"
[[LightGBM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4314a489c1f16a67e2820a9b64325c475ccf9903"
libc = "glibc"
os = "linux"

    [[LightGBM.download]]
    sha256 = "b88aef846e7bd80b658b1102e83a0310cb82b89f8546a4ec951e945c60de9b5e"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[LightGBM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81c1ff1da585286f0933d0bdb6d086f76cfe28fa"
libc = "glibc"
os = "linux"

    [[LightGBM.download]]
    sha256 = "0f0fc8eb527ea0e6fe78b872f3365a9271028d56bde8804263672b08f72077f0"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LightGBM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee748fb73655b3096353c6a70ebf6e66e89d312f"
libc = "musl"
os = "linux"

    [[LightGBM.download]]
    sha256 = "019c2f3fd08c35fd3d2362c897fa136f40041b486e00c1985e634800cc16aa43"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.armv6l-linux-musleabihf-cxx03.tar.gz"
[[LightGBM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cf7e27aea9294aa7656e80f72e039df84574530d"
libc = "musl"
os = "linux"

    [[LightGBM.download]]
    sha256 = "965779d5002084f5c485ce518f3b5c03d19307f8e5962d3e70c403c9ddacb4fb"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LightGBM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d718d95ab618623bafc02eac1b2e379e4350281f"
libc = "glibc"
os = "linux"

    [[LightGBM.download]]
    sha256 = "18d5b038fcb7d293ec6101a6e4fc39f09e47b78290a027956e5d06b10a8c8fce"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[LightGBM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af45343c84b6e5aaa5c88e5cd2490c0e41e52712"
libc = "glibc"
os = "linux"

    [[LightGBM.download]]
    sha256 = "0dc8e546fb51262623ef3cc272ddedd1a711adf0fbb8ef08cabe7875c080a9a9"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LightGBM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d4606b74b0b739efde0dd017a926ce3339410dd"
libc = "musl"
os = "linux"

    [[LightGBM.download]]
    sha256 = "f1a78652a542d0951aa1560f3764ac68dd6ea3d24754d07362a620598ffc910c"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[LightGBM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cda1d03216a590e09777151cf31011c63c4909e"
libc = "musl"
os = "linux"

    [[LightGBM.download]]
    sha256 = "76e153b1fdec6dccdf3740dd30046e83631f90d4411641b32f2a3360b2376b10"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LightGBM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "181d3fc314bc214766b5e410a083cdb1f6688712"
libc = "glibc"
os = "linux"

    [[LightGBM.download]]
    sha256 = "5629ff353da3ea75929d4349323bc0a956aca0b1999e79cf261f232b4fe50d77"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.i686-linux-gnu-cxx03.tar.gz"
[[LightGBM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "320f477dfbb83aa0200fcba94f8ff53f783fb13a"
libc = "glibc"
os = "linux"

    [[LightGBM.download]]
    sha256 = "070d92fa4b6159691b67d433c1d78b8a160b9142e85f9accdc3c4dfc708a0494"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.i686-linux-gnu-cxx11.tar.gz"
[[LightGBM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2cb751892384651bbfb2c50425764078eedf8b91"
libc = "musl"
os = "linux"

    [[LightGBM.download]]
    sha256 = "bc8b44c18bb4b2c70ac4a6a96d9ca217441535e8c59fb697b20918b62e575d3c"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.i686-linux-musl-cxx03.tar.gz"
[[LightGBM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "201d3d42002f2db58cce77b3415a9ab1af4b21c4"
libc = "musl"
os = "linux"

    [[LightGBM.download]]
    sha256 = "67233cfebb2e90c1007935aa1fbd3eb076dc9a5400143ccb9644efc4a5be3faa"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.i686-linux-musl-cxx11.tar.gz"
[[LightGBM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ffbfd156a1ebd619891d3748dfcf09d25c80de2"
os = "windows"

    [[LightGBM.download]]
    sha256 = "e50c63462856f0b27b95682ce40ac9cb24811cc45aeab866ee115f87bd09e174"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.i686-w64-mingw32-cxx03.tar.gz"
[[LightGBM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a3083a714a18fbc47516902c60a57b2962ad68ca"
os = "windows"

    [[LightGBM.download]]
    sha256 = "d77bd66e543a58dac9791d2159d9c58039886a48f10e9aced25da26338d85c4d"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.i686-w64-mingw32-cxx11.tar.gz"
[[LightGBM]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11005e99bc44d8d594c0a8d64c92e8321cfaf0bd"
libc = "glibc"
os = "linux"

    [[LightGBM.download]]
    sha256 = "64734ac95b32acd633e7f2caeb731f0049187645239b58aeb1f7721575240a50"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[LightGBM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bcfb4847656a7bb3ef8223cc2a6411bbf321416a"
libc = "glibc"
os = "linux"

    [[LightGBM.download]]
    sha256 = "da98a3029e1e24d77fe00dda376d901b20fda97d28d316d7052bc2bf1bdd193c"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LightGBM]]
arch = "x86_64"
git-tree-sha1 = "3fc3f65fa8c9dc80f75fcdce041da9d6207f600a"
os = "macos"

    [[LightGBM.download]]
    sha256 = "f179312db3c906e6b454251200b36e4dc9f124178a5b7b52fec6215ced86e558"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.x86_64-apple-darwin.tar.gz"
[[LightGBM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "980c3da0b963ed097b95fde119250467d9289a91"
libc = "glibc"
os = "linux"

    [[LightGBM.download]]
    sha256 = "a2656dd8d40ba1b99f68109b07965b007b499dd5e768f4ad498e214795189432"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.x86_64-linux-gnu-cxx03.tar.gz"
[[LightGBM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "540bed0735c8679d69fe1bd02524a14e8b8a10f2"
libc = "glibc"
os = "linux"

    [[LightGBM.download]]
    sha256 = "9819b1b9045791e22a1dabd9367686dd924c7c826ffbef8464f552cdb4b294e5"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.x86_64-linux-gnu-cxx11.tar.gz"
[[LightGBM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "30bc43bd067cf56b8ad40c36f42416757a968a51"
libc = "musl"
os = "linux"

    [[LightGBM.download]]
    sha256 = "983ab2b56fe3c5953fb0eb0fbc2a33433e9550523d048b2a897e162079a42eb6"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.x86_64-linux-musl-cxx03.tar.gz"
[[LightGBM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f03e841577755486e1f50ba634398d9b3266be56"
libc = "musl"
os = "linux"

    [[LightGBM.download]]
    sha256 = "592fccc6177aed4f371f739a55684a6facb5242a57b524e289deac293f3c8902"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.x86_64-linux-musl-cxx11.tar.gz"
[[LightGBM]]
arch = "x86_64"
git-tree-sha1 = "188b878aee31ddba984bede0a78ffb69180a4cd7"
os = "freebsd"

    [[LightGBM.download]]
    sha256 = "647a1324d04d6c70cd8880db6af57247b4327406957b5c7bda5d3110f9bbb164"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.x86_64-unknown-freebsd.tar.gz"
[[LightGBM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e874b75eb70a9a58154d8ddbafda70ac3035f3f"
os = "windows"

    [[LightGBM.download]]
    sha256 = "bd7709a58c8b133600607bd05d805233e959dd8c04f63b758d9805ffb4e5472a"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[LightGBM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2f678f4443812f4ae2d6676164ab14a28feb126"
os = "windows"

    [[LightGBM.download]]
    sha256 = "c9d5c413538349dcb85b8169e77edcbceddbb7f7877093eb7451df9ca4bc8638"
    url = "https://github.com/JuliaBinaryWrappers/LightGBM_jll.jl/releases/download/LightGBM-v3.3.5+1/LightGBM.v3.3.5.x86_64-w64-mingw32-cxx11.tar.gz"
