# Autogenerated wrapper script for LightGBM_jll for i686-w64-mingw32-cxx11
export lib_lightgbm, lightgbm

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("LightGBM")
JLLWrappers.@declare_library_product(lib_lightgbm, "lib_lightgbm.dll")
JLLWrappers.@declare_executable_product(lightgbm)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        lib_lightgbm,
        "bin\\lib_lightgbm.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        lightgbm,
        "bin\\lightgbm.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
